image: freebsd/latest
packages:
  - go
environment:
  PATH: "$PATH:`go env GOPATH`/bin"
sources:
  - https://github.com/mellium/sasl.git
tasks:
  - setup: |
      go version
      go env

      go get -u golang.org/x/lint/golint
      go get -u github.com/securego/gosec/cmd/gosec
  - fmt: |
      cd sasl/
      gofmt -s -l . && [ -z "$(gofmt -s -l .)" ]
  - vet: |
      cd sasl/
      go vet ./...
  - lint: |
      cd sasl/
      golint -set_exit_status ./...
  - gosec: |
      cd sasl/
      gosec ./...
  - validate: |
      cd xmpp/
      go mod tidy
      git diff --exit-code -- go.mod go.sum
  - stable: |
      cd sasl/
      go test -v -cover ./...
