image: golang:latest
pipelines:
  default:
    - step:
        script:
          - mkdir -p "$GOPATH/src/mellium.im/"
          - ln -s "`pwd`" "$GOPATH/src/mellium.im/sasl"
          - cd "$GOPATH/src/mellium.im/sasl"
          - go version
          - go get github.com/golang/dep/cmd/dep
          - dep ensure
          - go vet ./...
          - go test -race ./...
          - go test -cover -bench . -benchmem ./...
